# Use postgres/example user/password credentials
version: '3.7'

services:

  # server:
  #   container_name: server_api
  #   build: .
  #   command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
  #   ports:
  #     - "8001:8000"
  #   networks: 
  #     - apinet

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    networks: 
      - apinet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - apinet

networks:
  apinet:
      driver: bridge