# Generated by Django 3.0.8 on 2020-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontCenterDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('header_secs', models.PositiveIntegerField()),
                ('distance', models.CharField(max_length=15)),
            ],
        ),
    ]
