# Generated by Django 3.0.8 on 2020-08-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_secs', models.PositiveIntegerField()),
                ('temperature', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
