# Generated by Django 3.0.8 on 2020-08-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermometer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperatures',
            new_name='Temperature',
        ),
    ]
