# Generated by Django 3.0.8 on 2020-08-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controls',
            new_name='Control',
        ),
    ]
