# Generated by Django 3.0.8 on 2020-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoimage',
            name='video_image',
            field=models.ImageField(upload_to='video_images/'),
        ),
    ]
